name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0, 3.1, 3.2, 3.3]
        rails: [6.1.4]
        include:
          - ruby: 3.0
            rails: 6.1.4
          - ruby: 3.1
            rails: 6.1.4
          - ruby: 3.2
            rails: 6.1.4
          - ruby: 3.3
            rails: 6.1.4

    env:
      TESTING_RAILS_VERSION: ${{ matrix.rails }}

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          bundler: 2.3
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - run: bundle install

      - name: Run tests
        run: bundle exec rake
